// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhhUfe_lxTOiUqixBy6Kzxr1xyzEf_yA',
    appId: '1:1042531237919:web:136c513ffe7e470b1e552a',
    messagingSenderId: '1042531237919',
    projectId: 'fir-tutorial-c4e55',
    authDomain: 'fir-tutorial-c4e55.firebaseapp.com',
    storageBucket: 'fir-tutorial-c4e55.firebasestorage.app',
    measurementId: 'G-EBVDTCG9G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDQnbKbNOTkKWw8bdXVAxWxNEHzPa70o',
    appId: '1:1042531237919:android:684b52daf93fcfe91e552a',
    messagingSenderId: '1042531237919',
    projectId: 'fir-tutorial-c4e55',
    storageBucket: 'fir-tutorial-c4e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1ko_LAVvE0iNHOAxReD-Mt1Z1Yia_pM',
    appId: '1:1042531237919:ios:4c6002aed75474e91e552a',
    messagingSenderId: '1042531237919',
    projectId: 'fir-tutorial-c4e55',
    storageBucket: 'fir-tutorial-c4e55.firebasestorage.app',
    iosBundleId: 'com.example.projectWifiScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1ko_LAVvE0iNHOAxReD-Mt1Z1Yia_pM',
    appId: '1:1042531237919:ios:4c6002aed75474e91e552a',
    messagingSenderId: '1042531237919',
    projectId: 'fir-tutorial-c4e55',
    storageBucket: 'fir-tutorial-c4e55.firebasestorage.app',
    iosBundleId: 'com.example.projectWifiScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyhhUfe_lxTOiUqixBy6Kzxr1xyzEf_yA',
    appId: '1:1042531237919:web:1d7b634d568d5d4f1e552a',
    messagingSenderId: '1042531237919',
    projectId: 'fir-tutorial-c4e55',
    authDomain: 'fir-tutorial-c4e55.firebaseapp.com',
    storageBucket: 'fir-tutorial-c4e55.firebasestorage.app',
    measurementId: 'G-Y9SM8QZ8H2',
  );
}
